// ========================================
// NURSE ROBBY (ナースロビー) - 設定ファイル
// ブランド名・外部連携・表示設定を一括管理
// ========================================

const CONFIG = {
  // ブランド設定
  BRAND_NAME: "ナースロビー",
  TAGLINE: "採用のインフラを、再発明する",
  SITE_TITLE: "ナースロビー | 看護師の転職を手数料10%でまっすぐつなぐ【神奈川県】",
  META_DESCRIPTION: "看護師・理学療法士の転職手数料を一般的な紹介手数料の約半分、10%に。AIと人のハイブリッドで、あなたに最適な職場をご紹介。小田原・秦野・平塚・藤沢・海老名など神奈川県内の主要エリアに対応。",

  // 会社情報
  COMPANY: {
    name: "はるひメディカルサービス",
    representative: "平島禎之",
    licenseNumber: "23-ユ-302928",  // 有料職業紹介事業許可番号（厚生労働大臣許可）
    address: "神奈川県小田原市",       // 所在地（実住所に置換）
    email: "info@quads-nurse.com",
  },

  // 主要医療機関データ（病床機能報告R5＋医療情報ネット2025.12ベース）
  // referral: true = ナースロビーが直接紹介可能な契約施設
  // エリア: 県西12施設 + 湘南西部8施設 + 湘南東部2施設 + 県央1施設 = 計23施設
  HOSPITALS: [
    // ========== 県西（小田原・南足柄・箱根・松田） ==========
    {
      id: "kobayashi",
      displayName: "小林病院（小田原市・150床）",
      type: "急性期・回復期・慢性期",
      beds: 150,
      nurseCount: 54,
      doctorCount: 45,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅バス15分",
      nursingRatio: "13:1",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "ナースロビー紹介可能・ケアミックス・回復期リハビリ・ブランクOK・地域密着",
      referral: true,
    },
    {
      id: "odawara_city",
      displayName: "小田原市立病院（小田原市・417床）",
      type: "高度急性期・急性期",
      beds: 417,
      nurseCount: 386,
      doctorCount: 114,
      salary: "月給28〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "小田原駅バス10分",
      nursingRatio: "7:1",
      emergencyLevel: "三次救急",
      ownerType: "公立",
      features: "2026年新築移転予定・看護師386名・救命救急・災害拠点・ICU/NICU完備",
      referral: false,
    },
    {
      id: "ashigarakami",
      displayName: "神奈川県立足柄上病院（松田町・296床）",
      type: "急性期",
      beds: 296,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "松田駅バス5分",
      nursingRatio: "10:1",
      emergencyLevel: "二次救急",
      ownerType: "県立",
      features: "県立病院・地域医療の中核・教育体制充実・福利厚生充実",
      referral: false,
    },
    {
      id: "yamachika",
      displayName: "山近記念総合病院（小田原市・152床）",
      type: "急性期・回復期",
      beds: 152,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅バス10分",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "地域密着・二次救急・回復期リハビリ・ブランクOK",
      referral: false,
    },
    {
      id: "kouzuzu",
      displayName: "国府津病院（小田原市・250床）",
      type: "慢性期・回復期",
      beds: 250,
      salary: "月給25〜33万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "国府津駅徒歩10分",
      ownerType: "医療法人",
      features: "療養型・日勤のみ相談可・残業少なめ・ブランクOK",
      referral: false,
    },
    {
      id: "hakone_national",
      displayName: "国立病院機構箱根病院（小田原市・199床）",
      type: "回復期・慢性期",
      beds: 199,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅バス20分",
      ownerType: "国立病院機構",
      features: "国立病院・リハビリテーション・神経難病・教育体制充実・福利厚生充実",
      referral: false,
    },
    {
      id: "seisho",
      displayName: "西湘病院（小田原市・102床）",
      type: "回復期",
      beds: 102,
      salary: "月給26〜33万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鴨宮駅徒歩15分",
      ownerType: "医療法人",
      features: "回復期リハビリ・地域密着・残業少なめ・ブランクOK",
      referral: false,
    },
    {
      id: "kitaodawara",
      displayName: "北小田原病院（南足柄市・345床）",
      type: "回復期・慢性期",
      beds: 345,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "大雄山駅バス10分",
      ownerType: "医療法人",
      features: "大規模療養型・回復期リハビリ・日勤のみ相談可・残業少なめ",
      referral: false,
    },
    {
      id: "odawara_junkanki",
      displayName: "小田原循環器病院（小田原市・97床）",
      type: "急性期",
      beds: 97,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅バス10分",
      ownerType: "医療法人",
      features: "循環器専門・心臓カテーテル・急性期看護・専門性を活かせる",
      referral: false,
    },
    {
      id: "manaka",
      displayName: "間中病院（小田原市・90床）",
      type: "急性期・回復期",
      beds: 90,
      salary: "月給25〜33万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅徒歩10分",
      ownerType: "医療法人",
      features: "駅近・地域密着・アットホーム・ブランクOK",
      referral: false,
    },
    {
      id: "hakone_rehab",
      displayName: "箱根リハビリテーション病院（箱根町・109床）",
      type: "回復期",
      beds: 109,
      salary: "月給26〜33万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "箱根湯本駅バス15分",
      ownerType: "医療法人",
      features: "回復期リハビリ専門・温泉地・チーム医療・日勤のみ相談可",
      referral: false,
    },
    {
      id: "soga",
      displayName: "曽我病院（小田原市・297床）",
      type: "精神科",
      beds: 297,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "下曽我駅徒歩10分",
      ownerType: "医療法人",
      features: "精神科専門・デイケア・訪問看護・残業少なめ・夜勤手当高め",
      referral: false,
    },
    // ========== 湘南西部（平塚・秦野・伊勢原） ==========
    {
      id: "hiratsuka_kyosai",
      displayName: "平塚共済病院（平塚市・400床）",
      type: "高度急性期・急性期",
      beds: 400,
      nurseCount: 429,
      doctorCount: 122,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "平塚駅バス8分",
      nursingRatio: "7:1",
      emergencyLevel: "二次救急",
      ownerType: "公的",
      features: "地域医療支援病院・看護師429名・心臓センター・災害拠点",
      referral: false,
    },
    {
      id: "hiratsuka_city",
      displayName: "平塚市民病院（平塚市・416床）",
      type: "高度急性期・急性期",
      beds: 416,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "平塚駅バス10分",
      nursingRatio: "7:1",
      emergencyLevel: "二次救急",
      ownerType: "公立",
      features: "公立病院・地域がん拠点・災害拠点・教育体制充実・福利厚生充実",
      referral: false,
    },
    {
      id: "tokai_univ",
      displayName: "東海大学医学部付属病院（伊勢原市・804床）",
      type: "高度急性期",
      beds: 804,
      nurseCount: 1038,
      doctorCount: 550,
      salary: "月給30〜40万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "伊勢原駅バス10分",
      nursingRatio: "7:1",
      emergencyLevel: "三次救急",
      ownerType: "学校法人",
      features: "県西最大規模・看護師1038名・救命救急・大学病院・教育体制充実",
      referral: false,
    },
    {
      id: "hadano_redcross",
      displayName: "秦野赤十字病院（秦野市・308床）",
      type: "急性期",
      beds: 308,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "秦野駅バス5分",
      emergencyLevel: "二次救急",
      ownerType: "赤十字",
      features: "赤十字病院・地域医療支援・災害拠点・教育体制充実・福利厚生充実",
      referral: false,
    },
    {
      id: "tsurumaki",
      displayName: "鶴巻温泉病院（秦野市・505床）",
      type: "回復期・慢性期",
      beds: 505,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "鶴巻温泉駅徒歩3分",
      ownerType: "医療法人",
      features: "リハビリ大規模・駅徒歩3分・日勤のみ相談可・残業少なめ・ブランクOK",
      referral: false,
    },
    {
      id: "isehara_kyodo",
      displayName: "伊勢原協同病院（伊勢原市・350床）",
      type: "急性期",
      beds: 350,
      salary: "月給28〜36万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "伊勢原駅バス8分",
      emergencyLevel: "二次救急",
      ownerType: "公的",
      features: "地域医療支援・二次救急・教育体制充実・JA厚生連",
      referral: false,
    },
    {
      id: "saiseikai_hiratsuka",
      displayName: "済生会湘南平塚病院（平塚市・176床）",
      type: "急性期・回復期",
      beds: 176,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "平塚駅バス12分",
      ownerType: "公的",
      features: "済生会・地域密着・回復期リハビリ・ブランクOK・教育体制あり",
      referral: false,
    },
    {
      id: "kanagawa_national",
      displayName: "国立病院機構神奈川病院（秦野市・330床）",
      type: "急性期・慢性期",
      beds: 330,
      salary: "月給28〜36万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "秦野駅バス15分",
      ownerType: "国立病院機構",
      features: "国立病院・結核/呼吸器専門・教育体制充実・福利厚生充実",
      referral: false,
    },
    // ========== 湘南東部（藤沢・茅ヶ崎） ==========
    {
      id: "fujisawa_city",
      displayName: "藤沢市民病院（藤沢市・536床）",
      type: "高度急性期・急性期",
      beds: 536,
      nurseCount: 603,
      doctorCount: 184,
      salary: "月給30〜39万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "藤沢駅バス10分",
      nursingRatio: "7:1",
      emergencyLevel: "三次救急",
      ownerType: "公立",
      features: "公立病院・看護師603名・三次救急・ICU/NICU完備・地域医療支援病院",
      referral: false,
    },
    {
      id: "chigasaki_city",
      displayName: "茅ヶ崎市立病院（茅ヶ崎市・401床）",
      type: "高度急性期・急性期",
      beds: 401,
      nurseCount: 310,
      doctorCount: 104,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "北茅ヶ崎駅徒歩10分",
      nursingRatio: "7:1",
      emergencyLevel: "二次救急",
      ownerType: "公立",
      features: "公立病院・看護師310名・地域がん拠点・災害拠点・DMAT指定",
      referral: false,
    },
    // ========== 県央（海老名・厚木） ==========
    {
      id: "ebina_general",
      displayName: "海老名総合病院（海老名市・479床）",
      type: "高度急性期・急性期",
      beds: 479,
      nurseCount: 473,
      doctorCount: 148,
      salary: "月給30〜39万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "海老名駅東口徒歩12分",
      nursingRatio: "7:1",
      emergencyLevel: "三次救急",
      ownerType: "医療法人",
      features: "県央唯一の救命救急センター・看護師473名・PT54名・24時間救急",
      referral: false,
    },
  ],

  // 外部API連携（実運用時に設定）
  API: {
    workerEndpoint: "https://robby-the-match-api.robby-the-robot-2026.workers.dev",        // Cloudflare Workers API URL
    slackWebhookUrl: "",       // Slack Webhook URL（レガシー：workerEndpoint設定後は不要）
    googleSheetsId: "",        // Google Sheets ID（レガシー：workerEndpoint設定後は不要）
  },

  // デザイン設定
  DESIGN: {
    primaryBg: "#FAFAF2",
    secondaryBg: "#F2EFE6",
    accentColor: "#5B787D",
    accentSecondary: "#8FB5A1",
    accentHover: "#4A6368",
    textPrimary: "#4A4A4A",
    textSecondary: "#7A7A7A",
    cardBg: "#FFFFFF",
    borderColor: "#D4CFC2",
  },
};
