// ========================================
// NURSE ROBBY (神奈川ナース転職) - 設定ファイル
// ブランド名・外部連携・表示設定を一括管理
// ========================================

const CONFIG = {
  // ブランド設定
  BRAND_NAME: "神奈川ナース転職",
  TAGLINE: "採用のインフラを、再発明する",
  SITE_TITLE: "神奈川ナース転職 | 看護師の転職を手数料10%でまっすぐつなぐ【神奈川県】",
  META_DESCRIPTION: "看護師・理学療法士の転職手数料を一般的な紹介手数料の約半分、10%に。AIと人のハイブリッドで、あなたに最適な職場をご紹介。横浜・川崎・相模原・小田原など神奈川県全域の看護師求人に対応。",

  // 会社情報
  COMPANY: {
    name: "神奈川ナース転職",
    licenseNumber: "23-ユ-302928",  // 有料職業紹介事業許可番号（厚生労働大臣許可）
    address: "神奈川県小田原市",
    email: "info@quads-nurse.com",
  },

  // 主要医療機関データ（病床機能報告R5 + 医療情報ネット2025.12ベース + 2026.03精査）
  // referral: true = 神奈川ナース転職が直接紹介可能な契約施設
  // エリア: 県西17 + 湘南西部19 + 湘南東部15 + 県央26 + 横浜79 + 川崎28 + 相模原11 + 横須賀・三浦17 = 計212施設
  HOSPITALS: [
    // ========== 県西（小田原・南足柄・箱根・松田・湯河原） ==========
    {
      id: "kobayashi",
      displayName: "小林病院（小田原市・163床）",
      type: "急性期・回復期・慢性期",
      beds: 163,
      nurseCount: 54,
      doctorCount: 45,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅バス15分",
      nursingRatio: "13:1",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "神奈川ナース転職紹介可能・ケアミックス・回復期リハビリ・ブランクOK・地域密着",
      referral: true,
    },
    {
      id: "odawara_city",
      displayName: "小田原市立病院（小田原市・417床）",
      type: "高度急性期・急性期",
      beds: 417,
      nurseCount: 386,
      doctorCount: 114,
      salary: "月給28〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "小田原駅バス10分",
      nursingRatio: "7:1",
      emergencyLevel: "三次救急",
      ownerType: "公立",
      features: "2026年新築移転予定・看護師386名・救命救急・災害拠点・ICU/NICU完備",
      referral: false,
    },
    {
      id: "ashigarakami",
      displayName: "神奈川県立足柄上病院（松田町・296床）",
      type: "急性期",
      beds: 296,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "松田駅バス5分",
      nursingRatio: "10:1",
      emergencyLevel: "二次救急",
      ownerType: "県立",
      features: "県立病院・地域医療の中核・教育体制充実・福利厚生充実",
      referral: false,
    },
    {
      id: "yamachika",
      displayName: "山近記念総合病院（小田原市・152床）",
      type: "急性期・回復期",
      beds: 152,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅バス10分",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "地域密着・二次救急・回復期リハビリ・ブランクOK",
      referral: false,
    },
    {
      id: "kouzuzu",
      displayName: "国府津病院（小田原市・250床）",
      type: "慢性期・回復期",
      beds: 250,
      salary: "月給25〜33万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "国府津駅徒歩10分",
      ownerType: "医療法人",
      features: "療養型・日勤のみ相談可・残業少なめ・ブランクOK",
      referral: false,
    },
    {
      id: "hakone_national",
      displayName: "国立病院機構箱根病院（小田原市・199床）",
      type: "回復期・慢性期",
      beds: 199,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅バス20分",
      ownerType: "国立病院機構",
      features: "国立病院・リハビリテーション・神経難病・教育体制充実・福利厚生充実",
      referral: false,
    },
    {
      id: "seisho",
      displayName: "西湘病院（小田原市・102床）",
      type: "回復期",
      beds: 102,
      salary: "月給26〜33万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鴨宮駅徒歩15分",
      ownerType: "医療法人",
      features: "回復期リハビリ・地域密着・残業少なめ・ブランクOK",
      referral: false,
    },
    {
      id: "kitaodawara",
      displayName: "北小田原病院（南足柄市・345床）",
      type: "回復期・慢性期",
      beds: 345,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "大雄山駅バス10分",
      ownerType: "医療法人",
      features: "大規模療養型・回復期リハビリ・日勤のみ相談可・残業少なめ",
      referral: false,
    },
    {
      id: "odawara_junkanki",
      displayName: "小田原循環器病院（小田原市・97床）",
      type: "急性期",
      beds: 97,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅バス10分",
      ownerType: "医療法人",
      features: "循環器専門・心臓カテーテル・急性期看護・専門性を活かせる",
      referral: false,
    },
    {
      id: "manaka",
      displayName: "間中病院（小田原市・90床）",
      type: "急性期・回復期",
      beds: 90,
      salary: "月給25〜33万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "小田原駅徒歩10分",
      ownerType: "医療法人",
      features: "駅近・地域密着・アットホーム・ブランクOK",
      referral: false,
    },
    {
      id: "hakone_rehab",
      displayName: "箱根リハビリテーション病院（箱根町・191床）",
      type: "回復期",
      beds: 191,
      salary: "月給26〜33万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "箱根湯本駅バス15分",
      ownerType: "医療法人",
      features: "回復期リハビリ専門・温泉地・チーム医療・日勤のみ相談可",
      referral: false,
    },
    {
      id: "soga",
      displayName: "曽我病院（小田原市・297床）",
      type: "精神科",
      beds: 297,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "下曽我駅徒歩10分",
      ownerType: "医療法人",
      features: "精神科専門・デイケア・訪問看護・残業少なめ・夜勤手当高め",
      referral: false,
    },
    {
      id: "jcho_yugawara",
      displayName: "JCHO湯河原病院（湯河原町・150床）",
      type: "急性期",
      beds: 150,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "湯河原駅バス5分",
      emergencyLevel: "二次救急",
      ownerType: "独立行政法人JCHO",
      features: "JCHO（旧厚生年金病院）・湯河原真鶴エリアの中核・救急告示・福利厚生充実",
      referral: false,
    },
    // ===== 新規追加: 県西 =====
    {
      id: "katsumata_takadai",
      displayName: "勝又高台病院（開成町・310床）",
      type: "慢性期",
      beds: 310,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "開成駅徒歩10分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "yugawara_chuo_onsen",
      displayName: "湯河原中央温泉病院（湯河原町・223床）",
      type: "慢性期",
      beds: 223,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "湯河原駅バス10分",
      ownerType: "一般財団法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "ozawa",
      displayName: "小澤病院（小田原市・202床）",
      type: "急性期",
      beds: 202,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "小田原駅バス10分",
      ownerType: "医療法人",
      features: "地域密着",
      referral: false,
    },
    {
      id: "yugawara_icho",
      displayName: "湯河原胃腸病院（湯河原町・108床）",
      type: "急性期・慢性期",
      beds: 108,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "湯河原駅バス10分",
      ownerType: "医療法人",
      features: "地域密着・日勤のみ相談可",
      referral: false,
    },
    // ========== 湘南西部（平塚・秦野・伊勢原） ==========
    {
      id: "hiratsuka_kyosai",
      displayName: "平塚共済病院（平塚市・441床）",
      type: "高度急性期・急性期",
      beds: 441,
      nurseCount: 429,
      doctorCount: 122,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "平塚駅バス8分",
      nursingRatio: "7:1",
      emergencyLevel: "二次救急",
      ownerType: "公的",
      features: "地域医療支援病院・看護師429名・心臓センター・災害拠点",
      referral: false,
    },
    {
      id: "hiratsuka_city",
      displayName: "平塚市民病院（平塚市・416床）",
      type: "高度急性期・急性期",
      beds: 416,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "平塚駅バス10分",
      nursingRatio: "7:1",
      emergencyLevel: "二次救急",
      ownerType: "公立",
      features: "公立病院・地域がん拠点・災害拠点・教育体制充実・福利厚生充実",
      referral: false,
    },
    {
      id: "tokai_univ",
      displayName: "東海大学医学部付属病院（伊勢原市・804床）",
      type: "高度急性期",
      beds: 804,
      nurseCount: 1038,
      doctorCount: 550,
      salary: "月給30〜40万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "伊勢原駅バス10分",
      nursingRatio: "7:1",
      emergencyLevel: "三次救急",
      ownerType: "学校法人",
      features: "県西最大規模・看護師1038名・救命救急・大学病院・教育体制充実",
      referral: false,
    },
    {
      id: "hadano_redcross",
      displayName: "秦野赤十字病院（秦野市・308床）",
      type: "急性期",
      beds: 308,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "秦野駅バス5分",
      emergencyLevel: "二次救急",
      ownerType: "赤十字",
      features: "赤十字病院・地域医療支援・災害拠点・教育体制充実・福利厚生充実",
      referral: false,
    },
    {
      id: "tsurumaki",
      displayName: "鶴巻温泉病院（秦野市・557床）",
      type: "回復期・慢性期",
      beds: 557,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "鶴巻温泉駅徒歩3分",
      ownerType: "医療法人",
      features: "リハビリ大規模・駅徒歩3分・日勤のみ相談可・残業少なめ・ブランクOK",
      referral: false,
    },
    {
      id: "isehara_kyodo",
      displayName: "伊勢原協同病院（伊勢原市・350床）",
      type: "急性期",
      beds: 350,
      salary: "月給28〜36万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "伊勢原駅バス8分",
      emergencyLevel: "二次救急",
      ownerType: "公的",
      features: "地域医療支援・二次救急・教育体制充実・JA厚生連",
      referral: false,
    },
    {
      id: "saiseikai_hiratsuka",
      displayName: "済生会湘南平塚病院（平塚市・176床）",
      type: "急性期・回復期",
      beds: 176,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "平塚駅バス12分",
      ownerType: "公的",
      features: "済生会・地域密着・回復期リハビリ・ブランクOK・教育体制あり",
      referral: false,
    },
    {
      id: "kanagawa_national",
      displayName: "国立病院機構神奈川病院（秦野市・330床）",
      type: "急性期・慢性期",
      beds: 330,
      salary: "月給28〜36万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "秦野駅バス15分",
      ownerType: "国立病院機構",
      features: "国立病院・結核/呼吸器専門・教育体制充実・福利厚生充実",
      referral: false,
    },
    // ===== エージェント調査追加: 湘南西部 (11施設) =====
    {
      id: "tanzawa",
      displayName: "丹沢病院（秦野市・314床）",
      type: "精神科",
      beds: 314,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "渋沢駅バス10分",
      ownerType: "医療法人",
      features: "精神急性期治療50床・精神療養264床・残業少なめ",
      referral: false,
    },
    {
      id: "shonan_oiso",
      displayName: "湘南大磯病院（大磯町・312床）",
      type: "急性期",
      beds: 312,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "二宮駅バス10分",
      ownerType: "医療法人",
      features: "旧東海大大磯病院・徳洲会グループ・24時間救急・循環器カテーテル対応",
      referral: false,
    },
    {
      id: "fujimidai",
      displayName: "富士見台病院（平塚市・305床）",
      type: "精神科",
      beds: 305,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "平塚駅バス25分",
      ownerType: "医療法人",
      features: "精神科急性期41床・精神療養110床・残業少なめ",
      referral: false,
    },
    {
      id: "hiratsuka_mental",
      displayName: "平塚病院（平塚市・298床）",
      type: "精神科",
      beds: 298,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "平塚駅バス15分",
      ownerType: "医療法人",
      features: "精神科急性期・精神療養・認知症治療・残業少なめ",
      referral: false,
    },
    {
      id: "mikurube",
      displayName: "みくるべ病院（秦野市・276床）",
      type: "精神科",
      beds: 276,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "渋沢駅バス15分",
      ownerType: "医療法人",
      features: "認知症治療・依存症治療（アルコール・薬物）・残業少なめ",
      referral: false,
    },
    {
      id: "takane",
      displayName: "高根台病院（平塚市・236床）",
      type: "慢性期",
      beds: 236,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "平塚駅バス20分",
      ownerType: "医療法人",
      features: "療養型・介護病棟60床・リハビリ・日勤のみ相談可",
      referral: false,
    },
    {
      id: "hiratsuka_juzen",
      displayName: "平塚十全病院（平塚市・230床）",
      type: "急性期・慢性期",
      beds: 230,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "平塚駅バス15分",
      ownerType: "医療法人",
      features: "ケアミックス・障害者病棟・療養病棟・レスパイト入院対応",
      referral: false,
    },
    {
      id: "isehara_hinata",
      displayName: "伊勢原日向病院（伊勢原市・202床）",
      type: "慢性期",
      beds: 202,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "伊勢原駅バス20分",
      ownerType: "医療法人",
      features: "療養型・人工透析対応・日勤のみ相談可・残業少なめ",
      referral: false,
    },
    {
      id: "hadano_kosei",
      displayName: "秦野厚生病院（秦野市・160床）",
      type: "精神科",
      beds: 160,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "東海大学前駅徒歩10分",
      ownerType: "医療法人",
      features: "認知症病棟53床・精神急性期60床・残業少なめ",
      referral: false,
    },
    {
      id: "hadano_mental",
      displayName: "秦野病院（秦野市・151床）",
      type: "精神科",
      beds: 151,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "秦野駅バス15分",
      ownerType: "医療法人",
      features: "精神科デイケア・社会復帰支援・残業少なめ",
      referral: false,
    },
    {
      id: "fureai_hiratsuka",
      displayName: "ふれあい平塚ホスピタル（平塚市・125床）",
      type: "急性期・回復期",
      beds: 125,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "平塚駅徒歩10分",
      ownerType: "医療法人",
      features: "回復期リハビリ50床・障害者病棟40床・駅近",
      referral: false,
    },
    // ========== 湘南東部（藤沢・茅ヶ崎・鎌倉） ==========
    {
      id: "fujisawa_city",
      displayName: "藤沢市民病院（藤沢市・536床）",
      type: "高度急性期・急性期",
      beds: 536,
      nurseCount: 603,
      doctorCount: 184,
      salary: "月給30〜39万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "藤沢駅バス10分",
      nursingRatio: "7:1",
      emergencyLevel: "三次救急",
      ownerType: "公立",
      features: "公立病院・看護師603名・三次救急・ICU/NICU完備・地域医療支援病院",
      referral: false,
    },
    {
      id: "chigasaki_city",
      displayName: "茅ヶ崎市立病院（茅ヶ崎市・401床）",
      type: "高度急性期・急性期",
      beds: 401,
      nurseCount: 310,
      doctorCount: 104,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "北茅ヶ崎駅徒歩10分",
      nursingRatio: "7:1",
      emergencyLevel: "二次救急",
      ownerType: "公立",
      features: "公立病院・看護師310名・地域がん拠点・災害拠点・DMAT指定",
      referral: false,
    },
    {
      id: "shonan_fujisawa_tokushukai",
      displayName: "湘南藤沢徳洲会病院（藤沢市・419床）",
      type: "高度急性期・急性期",
      beds: 419,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "辻堂駅徒歩10分",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "徳洲会グループ・24時間救急・救急搬送多数・心臓血管外科・教育体制充実",
      referral: false,
    },
    {
      id: "fujisawa_shonandai",
      displayName: "藤沢湘南台病院（藤沢市・322床）",
      type: "急性期・回復期",
      beds: 322,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "湘南台駅徒歩10分",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "救急告示病院・地域密着・回復期リハビリ・ブランクOK",
      referral: false,
    },
    {
      id: "chigasaki_chuo",
      displayName: "茅ヶ崎中央病院（茅ヶ崎市・324床）",
      type: "急性期・回復期・慢性期",
      beds: 324,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "茅ヶ崎駅バス10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着・回復期リハビリ・療養病棟あり・ブランクOK",
      referral: false,
    },
    // ===== 新規追加: 湘南東部 =====
    {
      id: "shonan_tobu_sogo",
      displayName: "湘南東部総合病院（茅ヶ崎市・283床）",
      type: "高度急性期・急性期・回復期・慢性期",
      beds: 283,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "茅ヶ崎駅バス15分",
      ownerType: "医療法人",
      features: "高度医療・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "shonan_keiiku",
      displayName: "湘南慶育病院（藤沢市・230床）",
      type: "急性期・回復期",
      beds: 230,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "藤沢駅バス20分",
      ownerType: "医療法人",
      features: "回復期リハビリ・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "shonan_chuo",
      displayName: "湘南中央病院（藤沢市・199床）",
      type: "急性期・回復期・慢性期",
      beds: 199,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "藤沢駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "clover",
      displayName: "クローバーホスピタル（藤沢市・170床）",
      type: "回復期・慢性期",
      beds: 170,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "湘南台駅バス15分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "nagaoka",
      displayName: "長岡病院（茅ヶ崎市・162床）",
      type: "慢性期",
      beds: 162,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "茅ヶ崎駅バス15分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "fujisawa_goshomi",
      displayName: "藤沢御所見病院（藤沢市・154床）",
      type: "急性期・慢性期",
      beds: 154,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "湘南台駅バス10分",
      ownerType: "医療法人",
      features: "地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "chigasaki_tokushukai",
      displayName: "茅ヶ崎徳洲会病院（茅ヶ崎市・144床）",
      type: "高度急性期・急性期",
      beds: 144,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "茅ヶ崎駅バス10分",
      ownerType: "医療法人",
      features: "高度医療・徳洲会グループ・地域密着",
      referral: false,
    },
    {
      id: "shonan_chojuen",
      displayName: "湘南長寿園病院（藤沢市・120床）",
      type: "慢性期",
      beds: 120,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "藤沢駅バス20分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "shonan_hospital_hasegawa",
      displayName: "湘南ホスピタル（藤沢市・104床）",
      type: "回復期・慢性期",
      beds: 104,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "藤沢駅バス20分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    // ===== エージェント調査追加: 湘南東部 (1施設) =====
    {
      id: "keyaki_no_mori",
      displayName: "けやきの森病院（寒川町・184床）",
      type: "精神科",
      beds: 184,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "宮山駅徒歩5分",
      ownerType: "医療法人",
      features: "精神急性期44床・精神療養140床・駅近・残業少なめ",
      referral: false,
    },
    // ========== 県央（海老名・厚木・大和・座間） ==========
    {
      id: "ebina_general",
      displayName: "海老名総合病院（海老名市・479床）",
      type: "高度急性期・急性期",
      beds: 479,
      nurseCount: 473,
      doctorCount: 148,
      salary: "月給30〜39万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "海老名駅東口徒歩12分",
      nursingRatio: "7:1",
      emergencyLevel: "三次救急",
      ownerType: "医療法人",
      features: "県央唯一の救命救急センター・看護師473名・PT54名・24時間救急",
      referral: false,
    },
    {
      id: "atsugi_city",
      displayName: "厚木市立病院（厚木市・347床）",
      type: "急性期",
      beds: 347,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "本厚木駅バス10分",
      emergencyLevel: "二次救急",
      ownerType: "公立",
      features: "公立病院・地域がん拠点・災害拠点・救急告示・教育体制充実",
      referral: false,
    },
    {
      id: "yamato_city",
      displayName: "大和市立病院（大和市・403床）",
      type: "急性期",
      beds: 403,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "鶴間駅徒歩10分",
      emergencyLevel: "二次救急",
      ownerType: "公立",
      features: "公立病院・地域医療支援病院・災害拠点・がん診療連携・福利厚生充実",
      referral: false,
    },
    {
      id: "zama_general",
      displayName: "座間総合病院（座間市・352床）",
      type: "急性期・回復期",
      beds: 352,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "相武台前駅バス5分",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "救急告示病院・地域密着・座間市唯一の総合病院・ブランクOK",
      referral: false,
    },
    {
      id: "tomei_atsugi",
      displayName: "東名厚木病院（厚木市・282床）",
      type: "急性期",
      beds: 282,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "愛甲石田駅バス10分",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "IMSグループ・二次救急・循環器・消化器・教育体制あり",
      referral: false,
    },
    {
      id: "jcho_sagamino",
      displayName: "JCHO相模野病院（相模原市南区・212床）",
      type: "急性期",
      beds: 212,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "相模大野駅バス10分",
      ownerType: "独立行政法人JCHO",
      features: "JCHO（旧社会保険病院）・地域密着・福利厚生充実・ブランクOK",
      referral: false,
    },
    {
      id: "yamato_tokushukai",
      displayName: "大和徳洲会病院（大和市・248床）",
      type: "急性期",
      beds: 248,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "大和駅徒歩5分",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "徳洲会グループ・2018年新築移転・駅徒歩5分・救急告示・27診療科",
      referral: false,
    },
    // ===== エージェント調査追加: 県央 (19施設) =====
    {
      id: "aiko",
      displayName: "愛光病院（厚木市・359床）",
      type: "精神科",
      beds: 359,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "本厚木駅バス15分",
      ownerType: "医療法人",
      features: "精神科専門・大規模・夜勤手当高め・残業少なめ",
      referral: false,
    },
    {
      id: "kiyokawa_enju",
      displayName: "清川遠寿病院（清川村・325床）",
      type: "精神科",
      beds: 325,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "本厚木駅バス40分",
      ownerType: "医療法人",
      features: "精神科専門・依存症治療・残業少なめ",
      referral: false,
    },
    {
      id: "kanagawa_rehab",
      displayName: "神奈川リハビリテーション病院（厚木市・324床）",
      type: "回復期",
      beds: 324,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "愛甲石田駅バス20分",
      ownerType: "県立",
      features: "県立リハビリ専門・脊髄損傷・脳血管障害・高度リハビリテーション・教育体制充実",
      referral: false,
    },
    {
      id: "sagamidai",
      displayName: "相模台病院（座間市・306床）",
      type: "急性期・慢性期",
      beds: 306,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "小田急相模原駅徒歩10分",
      ownerType: "医療法人",
      features: "精神科併設・外科・整形外科・地域包括医療・地域密着",
      referral: false,
    },
    {
      id: "soshu",
      displayName: "相州病院（厚木市・263床）",
      type: "精神科",
      beds: 263,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "本厚木駅バス20分",
      ownerType: "医療法人",
      features: "精神急性期120床・認知症治療・児童思春期外来",
      referral: false,
    },
    {
      id: "shonan_atsugi",
      displayName: "湘南厚木病院（厚木市・253床）",
      type: "急性期・回復期",
      beds: 253,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "愛甲石田駅バス10分",
      ownerType: "医療法人",
      features: "徳洲会グループ・救急告示病院・回復期リハビリ・HCU10床・教育体制あり",
      referral: false,
    },
    {
      id: "aoi_nanasawa_rehab",
      displayName: "AOI七沢リハビリテーション病院（厚木市・245床）",
      type: "回復期",
      beds: 245,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "愛甲石田駅バス20分",
      ownerType: "医療法人",
      features: "全床回復期リハビリ・透析対応・日勤のみ相談可",
      referral: false,
    },
    {
      id: "sobudai_rehab",
      displayName: "相武台リハビリテーション病院（座間市・243床）",
      type: "回復期・慢性期",
      beds: 243,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "相武台前駅徒歩10分",
      ownerType: "医療法人",
      features: "回復期リハビリ80床・療養119床・日勤のみ相談可",
      referral: false,
    },
    {
      id: "shoyo_kashiwadai",
      displayName: "湘陽かしわ台病院（海老名市・199床）",
      type: "急性期・回復期・慢性期",
      beds: 199,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "かしわ台駅徒歩5分",
      ownerType: "医療法人",
      features: "駅近・ケアミックス・回復期リハビリ80床・日勤のみ相談可",
      referral: false,
    },
    {
      id: "atsugi_sato",
      displayName: "厚木佐藤病院（厚木市・184床）",
      type: "急性期・回復期・慢性期",
      beds: 184,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "愛甲石田駅バス10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域包括ケア・認知症治療・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "kanagawa_chuo_mental",
      displayName: "神奈川中央病院（厚木市・180床）",
      type: "精神科",
      beds: 180,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "本厚木駅バス15分",
      ownerType: "医療法人",
      features: "認知症専門・残業少なめ・日勤のみ相談可",
      referral: false,
    },
    {
      id: "sakuragaoka_chuo",
      displayName: "桜ヶ丘中央病院（大和市・171床）",
      type: "急性期・回復期",
      beds: 171,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "桜ヶ丘駅徒歩5分",
      ownerType: "医療法人",
      features: "回復期リハビリ86床・駅近・ケアミックス・日勤のみ相談可",
      referral: false,
    },
    {
      id: "ayase_kosei",
      displayName: "綾瀬厚生病院（綾瀬市・168床）",
      type: "急性期・慢性期",
      beds: 168,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "海老名駅バス15分",
      ownerType: "医療法人",
      features: "救急告示病院・ケアミックス・回復期リハビリ・地域密着",
      referral: false,
    },
    {
      id: "oasis_shonan",
      displayName: "オアシス湘南病院（海老名市・158床）",
      type: "慢性期",
      beds: 158,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "本厚木駅バス15分",
      ownerType: "医療法人",
      features: "療養型・入院透析対応・リハビリ充実・日勤のみ相談可",
      referral: false,
    },
    {
      id: "aikawa_hokubu",
      displayName: "愛川北部病院（愛川町・150床）",
      type: "急性期・慢性期",
      beds: 150,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "本厚木駅バス30分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "minami_yamato",
      displayName: "南大和病院（大和市・140床）",
      type: "急性期・回復期",
      beds: 140,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "高座渋谷駅バス5分",
      ownerType: "医療法人",
      features: "回復期リハビリ・人間ドック・地域密着",
      referral: false,
    },
    {
      id: "jinkokai",
      displayName: "仁厚会病院（厚木市・131床）",
      type: "急性期・慢性期",
      beds: 131,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "本厚木駅徒歩5分",
      ownerType: "医療法人",
      features: "駅徒歩5分・ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "chuo_rinkan",
      displayName: "中央林間病院（大和市・116床）",
      type: "急性期",
      beds: 116,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "中央林間駅徒歩2分",
      ownerType: "社会医療法人",
      features: "駅徒歩2分・地域包括ケア・地域密着",
      referral: false,
    },
    {
      id: "kondo",
      displayName: "近藤病院（厚木市・112床）",
      type: "急性期",
      beds: 112,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "本厚木駅バス5分",
      ownerType: "医療法人",
      features: "脳神経外科・救急告示病院・地域密着",
      referral: false,
    },
    // ========== 横浜（横浜市） ==========
    {
      id: "yokohama_city_univ",
      displayName: "横浜市立大学附属病院（横浜市金沢区・671床）",
      type: "高度急性期・急性期",
      beds: 671,
      salary: "月給28〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "シーサイドライン市大医学部駅徒歩1分",
      ownerType: "公立大学法人",
      features: "大学病院・教育体制充実・専門看護師育成・高度医療・特定機能病院",
      referral: false,
    },
    {
      id: "yokohama_city_univ_center",
      displayName: "横浜市立大学附属市民総合医療センター（横浜市南区・655床）",
      type: "高度急性期・急性期",
      beds: 655,
      salary: "月給28〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "阪東橋駅徒歩5分",
      ownerType: "公立大学法人",
      features: "大学病院・高度救命救急センター・周産期母子医療・特定機能病院",
      referral: false,
    },
    {
      id: "yokohama_minato_redcross",
      displayName: "横浜市立みなと赤十字病院（横浜市中区・624床）",
      type: "高度急性期・急性期",
      beds: 624,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "元町・中華街駅徒歩18分",
      ownerType: "赤十字",
      features: "赤十字病院・救命救急・災害拠点・精神科救急・がん診療連携拠点",
      referral: false,
    },
    {
      id: "saiseikai_yokohama_tobu",
      displayName: "済生会横浜市東部病院（横浜市鶴見区・562床）",
      type: "高度急性期・急性期",
      beds: 562,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "鶴見駅バス10分",
      ownerType: "公的",
      features: "済生会・救命救急・地域医療支援病院・がん診療連携拠点・教育体制充実",
      referral: false,
    },
    {
      id: "showa_fujigaoka",
      displayName: "昭和大学藤が丘病院（横浜市青葉区・584床）",
      type: "高度急性期・急性期",
      beds: 584,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "藤が丘駅徒歩1分",
      ownerType: "学校法人",
      features: "大学病院・駅直結・救急告示病院・災害拠点・教育体制充実",
      referral: false,
    },
    {
      id: "yokohama_rosai",
      displayName: "横浜労災病院（横浜市港北区・650床）",
      type: "高度急性期・急性期",
      beds: 650,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "新横浜駅徒歩7分",
      ownerType: "独立行政法人",
      features: "労災病院・新横浜駅近・救命救急センター・地域医療支援病院・教育体制充実",
      referral: false,
    },
    {
      id: "keiyu",
      displayName: "けいゆう病院（横浜市西区・410床）",
      type: "急性期",
      beds: 410,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "みなとみらい駅徒歩3分",
      ownerType: "一般財団法人",
      features: "みなとみらい立地・駅徒歩3分・地域医療支援病院・歴史ある病院",
      referral: false,
    },
    {
      id: "yokohama_minami_kyosai",
      displayName: "横浜南共済病院（横浜市金沢区・565床）",
      type: "高度急性期・急性期",
      beds: 565,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "追浜駅徒歩10分",
      ownerType: "公的",
      features: "救命救急センター・地域医療支援病院・災害拠点・がん診療連携拠点・緩和ケア病棟",
      referral: false,
    },
    {
      id: "yokohama_shimin",
      displayName: "横浜市立市民病院（横浜市神奈川区・650床）",
      type: "高度急性期・急性期",
      beds: 650,
      salary: "月給30〜39万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "三ツ沢上町駅バス5分",
      ownerType: "公立",
      features: "公立病院・がん診療連携拠点・救命救急・感染症指定・小児救急",
      referral: false,
    },
    {
      id: "showa_hokubu",
      displayName: "昭和大学横浜市北部病院（横浜市都筑区・696床）",
      type: "高度急性期・急性期",
      beds: 696,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "センター南駅徒歩6分",
      ownerType: "学校法人",
      features: "大学病院・駅近・救命救急センター・がん診療連携拠点・教育体制充実",
      referral: false,
    },
    {
      id: "st_marianna_seibu",
      displayName: "聖マリアンナ医科大学横浜市西部病院（横浜市旭区・518床）",
      type: "高度急性期・急性期",
      beds: 518,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "三ツ境駅バス15分",
      emergencyLevel: "三次救急",
      ownerType: "学校法人",
      features: "大学病院・救命救急センター・地域医療支援病院・災害拠点・教育体制充実",
      referral: false,
    },
    {
      id: "yokohama_medical_center",
      displayName: "横浜医療センター（横浜市戸塚区・490床）",
      type: "高度急性期・急性期",
      beds: 490,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "戸塚駅バス10分",
      emergencyLevel: "三次救急",
      ownerType: "国立病院機構",
      features: "国立病院機構・救命救急センター・地域がん拠点・災害拠点・教育体制充実",
      referral: false,
    },
    {
      id: "yokohama_asahi_chuo",
      displayName: "横浜旭中央総合病院（横浜市旭区・515床）",
      type: "急性期・回復期・慢性期",
      beds: 515,
      salary: "月給27〜36万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "若葉台駅バス10分",
      emergencyLevel: "二次救急",
      ownerType: "医療法人",
      features: "IMSグループ・ケアミックス・回復期リハビリ・地域密着・教育体制あり",
      referral: false,
    },
    {
      id: "saiseikai_yokohama_nanbu",
      displayName: "済生会横浜市南部病院（横浜市港南区・500床）",
      type: "高度急性期・急性期",
      beds: 500,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "港南台駅徒歩3分",
      emergencyLevel: "二次救急",
      ownerType: "公的",
      features: "済生会・駅徒歩3分・地域医療支援病院・災害拠点・教育体制充実",
      referral: false,
    },
    {
      id: "yokohama_sakae_kyosai",
      displayName: "横浜栄共済病院（横浜市栄区・430床）",
      type: "急性期",
      beds: 430,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "本郷台駅徒歩7分",
      emergencyLevel: "二次救急",
      ownerType: "公的",
      features: "共済病院・駅近・地域医療支援病院・がん診療連携・教育体制充実",
      referral: false,
    },
    {
      id: "seirei_yokohama",
      displayName: "聖隷横浜病院（横浜市保土ケ谷区・367床）",
      type: "急性期",
      beds: 367,
      salary: "月給28〜36万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "保土ケ谷駅バス5分",
      emergencyLevel: "二次救急",
      ownerType: "社会福祉法人",
      features: "聖隷グループ・救急告示病院・地域密着・教育体制充実・福利厚生充実",
      referral: false,
    },
    {
      id: "kokusai_shinzen",
      displayName: "国際親善総合病院（横浜市泉区・287床）",
      type: "急性期",
      beds: 287,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "弥生台駅徒歩7分",
      emergencyLevel: "二次救急",
      ownerType: "社会福祉法人",
      features: "駅近・救急告示病院・地域密着・教育体制あり・ブランクOK",
      referral: false,
    },
    {
      id: "kanagawa_cancer_center",
      displayName: "神奈川県立がんセンター（横浜市旭区・415床）",
      type: "高度急性期・急性期",
      beds: 415,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "二俣川駅バス5分",
      ownerType: "地方独立行政法人",
      features: "がん専門病院・都道府県がん拠点・重粒子線治療i-ROCK・がん看護専門・教育体制充実",
      referral: false,
    },
    // ===== 新規追加: 横浜 =====
    {
      id: "kanagawa_kodomo",
      displayName: "神奈川県立こども医療センター（横浜市南区・390床）",
      type: "高度急性期・急性期・回復期・慢性期",
      beds: 390,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "弘明寺駅バス10分",
      ownerType: "県立",
      features: "高度医療・公立病院・ケアミックス・小児専門・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "yokohama_denentoshi",
      displayName: "横浜田園都市病院（横浜市緑区・375床）",
      type: "慢性期",
      beds: 375,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "長津田駅バス10分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "ims_higashi_totsuka_rehab",
      displayName: "IMS横浜東戸塚総合リハビリテーション病院（横浜市戸塚区・333床）",
      type: "回復期・慢性期",
      beds: 333,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "東戸塚駅バス5分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・IMSグループ・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "ushioda",
      displayName: "汐田総合病院（横浜市鶴見区・324床）",
      type: "急性期・回復期",
      beds: 324,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "鶴見駅徒歩10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "yokohama_shintoshi_noge",
      displayName: "横浜新都市脳神経外科病院（横浜市青葉区・317床）",
      type: "高度急性期・急性期・回復期",
      beds: 317,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（三交代制）",
      commute: "あざみ野駅バス10分",
      ownerType: "医療法人",
      features: "高度医療・IMSグループ・ケアミックス・脳神経外科・地域密着",
      referral: false,
    },
    {
      id: "higashi_totsuka_kinen",
      displayName: "東戸塚記念病院（横浜市戸塚区・304床）",
      type: "高度急性期・急性期・回復期",
      beds: 304,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（三交代制）",
      commute: "東戸塚駅バス5分",
      ownerType: "医療法人",
      features: "高度医療・ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "yokohama_sogo",
      displayName: "横浜総合病院（横浜市青葉区・300床）",
      type: "高度急性期・急性期",
      beds: 300,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（三交代制）",
      commute: "青葉台駅バス10分",
      ownerType: "医療法人",
      features: "高度医療・地域密着",
      referral: false,
    },
    {
      id: "yokohama_nousocchu",
      displayName: "横浜市立脳卒中・神経脊椎センター（横浜市磯子区・300床）",
      type: "高度急性期・急性期・回復期",
      beds: 300,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "新杉田駅バス10分",
      ownerType: "公立",
      features: "高度医療・回復期リハビリ・公立病院・ケアミックス・脳神経外科・地域密着",
      referral: false,
    },
    {
      id: "jcho_yokohama_chuo",
      displayName: "JCHO横浜中央病院（横浜市中区・250床）",
      type: "高度急性期・急性期・回復期",
      beds: 250,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "石川町駅徒歩10分",
      ownerType: "独立行政法人JCHO",
      features: "高度医療・JCHO・ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "yokohama_shinryoku",
      displayName: "横浜新緑総合病院（横浜市緑区・236床）",
      type: "高度急性期・急性期・回復期",
      beds: 236,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "十日市場駅バス5分",
      ownerType: "医療法人",
      features: "高度医療・ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "jcho_hodogaya",
      displayName: "JCHO横浜保土ケ谷中央病院（横浜市保土ケ谷区・236床）",
      type: "高度急性期・急性期",
      beds: 236,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "保土ケ谷駅バス10分",
      ownerType: "独立行政法人JCHO",
      features: "高度医療・JCHO・地域密着",
      referral: false,
    },
    {
      id: "shin_yokohama_rehab",
      displayName: "新横浜リハビリテーション病院（横浜市神奈川区・230床）",
      type: "回復期・慢性期",
      beds: 230,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "新横浜駅バス5分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "yokohama_tsurumi_rehab",
      displayName: "横浜鶴見リハビリテーション病院（横浜市鶴見区・228床）",
      type: "回復期・慢性期",
      beds: 228,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鶴見駅バス15分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "shiomidai",
      displayName: "汐見台病院（横浜市磯子区・225床）",
      type: "急性期・回復期・慢性期",
      beds: 225,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "磯子駅バス10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "yokohama_namiki_rehab",
      displayName: "横浜なみきリハビリテーション病院（横浜市金沢区・224床）",
      type: "回復期・慢性期",
      beds: 224,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "並木北駅徒歩5分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "yokohama_genki",
      displayName: "横浜病院（横浜市緑区・220床）",
      type: "慢性期",
      beds: 220,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "中山駅バス10分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "kikuna_kinen",
      displayName: "菊名記念病院（横浜市港北区・218床）",
      type: "高度急性期・急性期",
      beds: 218,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "菊名駅徒歩10分",
      ownerType: "医療法人",
      features: "高度医療・地域密着",
      referral: false,
    },
    {
      id: "yamamoto_kinen",
      displayName: "山本記念病院（横浜市都筑区・213床）",
      type: "急性期・慢性期",
      beds: 213,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "センター北駅バス5分",
      ownerType: "医療法人",
      features: "地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "fureai_tsurumi",
      displayName: "ふれあい鶴見ホスピタル（横浜市鶴見区・210床）",
      type: "回復期・慢性期",
      beds: 210,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鶴見駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "saiseikai_kanagawa",
      displayName: "済生会神奈川県病院（横浜市神奈川区・199床）",
      type: "急性期・回復期・慢性期",
      beds: 199,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "東神奈川駅徒歩10分",
      ownerType: "公的",
      features: "済生会・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "akaeda",
      displayName: "赤枝病院（横浜市旭区・199床）",
      type: "慢性期",
      beds: 199,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鶴ヶ峰駅バス10分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "kanto_isogo",
      displayName: "関東病院（横浜市磯子区・199床）",
      type: "回復期・慢性期",
      beds: 199,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "磯子駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "showa_fujigaoka_rehab",
      displayName: "昭和大学藤が丘リハビリテーション病院（横浜市青葉区・197床）",
      type: "急性期・回復期",
      beds: 197,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "藤が丘駅徒歩5分",
      ownerType: "学校法人",
      features: "回復期リハビリ・大学病院・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "nishi_yokohama_kokusai",
      displayName: "西横浜国際総合病院（横浜市戸塚区・188床）",
      type: "急性期・回復期",
      beds: 188,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "戸塚駅バス10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "makino_kinen",
      displayName: "牧野記念病院（横浜市緑区・183床）",
      type: "急性期・回復期・慢性期",
      beds: 183,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "長津田駅バス10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "heisei_yokohama",
      displayName: "平成横浜病院（横浜市戸塚区・183床）",
      type: "急性期・回復期",
      beds: 183,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "戸塚駅バス15分",
      ownerType: "医療法人",
      features: "回復期リハビリ・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "isogo_chuo",
      displayName: "磯子中央病院（横浜市磯子区・180床）",
      type: "急性期・回復期",
      beds: 180,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "根岸駅徒歩10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "kanagawa_junkanki_kokyuki",
      displayName: "神奈川県立循環器呼吸器病センター（横浜市金沢区・179床）",
      type: "高度急性期・急性期",
      beds: 179,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "能見台駅バス10分",
      ownerType: "県立",
      features: "高度医療・公立病院・循環器・呼吸器専門・地域密着",
      referral: false,
    },
    {
      id: "eda_kinen",
      displayName: "江田記念病院（横浜市青葉区・177床）",
      type: "回復期・慢性期",
      beds: 177,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "江田駅徒歩5分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・IMSグループ・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "wakakusa",
      displayName: "済生会若草病院（横浜市金沢区・177床）",
      type: "回復期",
      beds: 177,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "金沢文庫駅バス10分",
      ownerType: "公的",
      features: "回復期リハビリ・済生会・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "yokohama_izumidai",
      displayName: "横浜いずみ台病院（横浜市泉区・176床）",
      type: "慢性期",
      beds: 176,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "弥生台駅バス5分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "aoba_sawai",
      displayName: "青葉さわい病院（横浜市青葉区・170床）",
      type: "回復期・慢性期",
      beds: 170,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "市が尾駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "oguchihigashi",
      displayName: "大口東総合病院（横浜市神奈川区・162床）",
      type: "急性期",
      beds: 162,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "子安駅徒歩5分",
      ownerType: "医療法人",
      features: "地域密着",
      referral: false,
    },
    {
      id: "yumegaoka",
      displayName: "ゆめが丘総合病院（横浜市泉区・156床）",
      type: "急性期",
      beds: 156,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "ゆめが丘駅徒歩5分",
      ownerType: "医療法人",
      features: "地域密着",
      referral: false,
    },
    {
      id: "yokohama_ekisaikai",
      displayName: "横浜掖済会病院（横浜市中区・151床）",
      type: "急性期",
      beds: 151,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "石川町駅バス5分",
      ownerType: "医療法人",
      features: "地域密着",
      referral: false,
    },
    {
      id: "kamoi",
      displayName: "鴨居病院（横浜市緑区・150床）",
      type: "急性期・慢性期",
      beds: 150,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鴨居駅バス5分",
      ownerType: "医療法人",
      features: "地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "kamishirane",
      displayName: "上白根病院（横浜市旭区・150床）",
      type: "急性期・回復期",
      beds: 150,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "中山駅バス15分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "fureai_higashi_totsuka",
      displayName: "ふれあい東戸塚ホスピタル（横浜市戸塚区・150床）",
      type: "回復期・慢性期",
      beds: 150,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "東戸塚駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "totsuka_kyoritsu1",
      displayName: "戸塚共立第1病院（横浜市戸塚区・148床）",
      type: "急性期",
      beds: 148,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "戸塚駅バス5分",
      ownerType: "医療法人",
      features: "地域密着",
      referral: false,
    },
    {
      id: "ims_yokohama_kariba",
      displayName: "IMS横浜狩場脳神経外科病院（横浜市保土ケ谷区・147床）",
      type: "高度急性期・急性期・回復期",
      beds: 147,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "井土ヶ谷駅バス10分",
      ownerType: "医療法人",
      features: "高度医療・回復期リハビリ・IMSグループ・ケアミックス・脳神経外科・地域密着",
      referral: false,
    },
    {
      id: "kanazawa_bunko",
      displayName: "金沢文庫病院（横浜市金沢区・147床）",
      type: "急性期・慢性期",
      beds: 147,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "金沢文庫駅徒歩10分",
      ownerType: "医療法人",
      features: "地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "heiwa",
      displayName: "平和病院（横浜市鶴見区・146床）",
      type: "急性期・回復期・慢性期",
      beds: 146,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鶴見駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "midori_kyowa",
      displayName: "緑協和病院（横浜市青葉区・145床）",
      type: "回復期・慢性期",
      beds: 145,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "青葉台駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "shinnakagawa",
      displayName: "新中川病院（横浜市泉区・145床）",
      type: "慢性期",
      beds: 145,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "いずみ中央駅バス10分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "tachibanadai",
      displayName: "たちばな台病院（横浜市青葉区・134床）",
      type: "急性期",
      beds: 134,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "青葉台駅バス10分",
      ownerType: "医療法人",
      features: "地域密着",
      referral: false,
    },
    {
      id: "tsuzuki",
      displayName: "つづき病院（横浜市都筑区・123床）",
      type: "慢性期",
      beds: 123,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "センター南駅バス10分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "kanazawa_keisui",
      displayName: "金沢病院（横浜市金沢区・121床）",
      type: "急性期・回復期",
      beds: 121,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "金沢八景駅バス10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "makino_rehab",
      displayName: "牧野リハビリテーション病院（横浜市緑区・120床）",
      type: "回復期・慢性期",
      beds: 120,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "十日市場駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "ichigao",
      displayName: "市ヶ尾病院（横浜市青葉区・120床）",
      type: "回復期・慢性期",
      beds: 120,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "市が尾駅徒歩5分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "ims_yokohama_asahi_rehab",
      displayName: "IMS横浜旭リハビリテーション病院（横浜市旭区・120床）",
      type: "回復期",
      beds: 120,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鶴ヶ峰駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・IMSグループ・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "konandai_houkatsu",
      displayName: "よこはま港南台地域包括ケア病院（横浜市港南区・120床）",
      type: "回復期",
      beds: 120,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "港南台駅バス5分",
      ownerType: "医療法人",
      features: "回復期リハビリ・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "shin_yokohama_kokoro",
      displayName: "新横浜こころのホスピタル（横浜市港北区・118床）",
      type: "慢性期",
      beds: 118,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "新横浜駅バス10分",
      ownerType: "医療法人",
      features: "療養型・精神科・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "sato",
      displayName: "佐藤病院（横浜市南区・116床）",
      type: "急性期・回復期",
      beds: 116,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "弘明寺駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "okurayama_kinen",
      displayName: "大倉山記念病院（横浜市港北区・114床）",
      type: "回復期・慢性期",
      beds: 114,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "大倉山駅徒歩5分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "yokohama_tsurugamine",
      displayName: "横浜鶴ヶ峰病院（横浜市旭区・108床）",
      type: "急性期",
      beds: 108,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鶴ヶ峰駅徒歩10分",
      ownerType: "医療法人",
      features: "地域密着",
      referral: false,
    },
    {
      id: "higashi_kanagawa_rehab",
      displayName: "済生会東神奈川リハビリテーション病院（横浜市神奈川区・106床）",
      type: "回復期",
      beds: 106,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "東神奈川駅徒歩5分",
      ownerType: "公的",
      features: "回復期リハビリ・済生会・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "ikuseikai_yokohama",
      displayName: "育生会横浜病院（横浜市保土ケ谷区・106床）",
      type: "回復期・慢性期",
      beds: 106,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "天王町駅徒歩10分",
      ownerType: "一般財団法人",
      features: "回復期リハビリ・療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "totsuka_kyoritsu2",
      displayName: "戸塚共立第2病院（横浜市戸塚区・101床）",
      type: "高度急性期・急性期",
      beds: 101,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "戸塚駅バス10分",
      ownerType: "医療法人",
      features: "高度医療・地域密着",
      referral: false,
    },
    {
      id: "totsuka_kyoritsu_izumino",
      displayName: "戸塚共立いずみ野病院（横浜市泉区・100床）",
      type: "急性期・回復期",
      beds: 100,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "いずみ野駅バス5分",
      ownerType: "医療法人",
      features: "回復期リハビリ・ケアミックス・地域密着",
      referral: false,
    },
    // ===== エージェント調査追加: 横浜 (2施設) =====
    {
      id: "yokohama_aihara",
      displayName: "横浜相原病院（横浜市瀬谷区・343床）",
      type: "精神科",
      beds: 343,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "希望ヶ丘駅バス10分",
      ownerType: "医療法人",
      features: "精神科専門・認知症から思春期まで対応・特定行為看護師在籍・AMGグループ",
      referral: false,
    },
    {
      id: "washinzaka",
      displayName: "ワシン坂病院（横浜市中区・167床）",
      type: "精神科",
      beds: 167,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "石川町駅徒歩15分",
      ownerType: "医療法人",
      features: "精神科・心療内科・山手の丘・残業少なめ",
      referral: false,
    },
    // ========== 川崎（川崎市） ==========
    {
      id: "st_marianna",
      displayName: "聖マリアンナ医科大学病院（川崎市宮前区・955床）",
      type: "高度急性期・急性期",
      beds: 955,
      salary: "月給29〜39万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "宮前平駅・鷺沼駅バス約15分",
      ownerType: "学校法人",
      features: "大学病院・特定機能病院・救命救急センター・高度医療・教育体制充実",
      referral: false,
    },
    {
      id: "kawasaki_city",
      displayName: "川崎市立川崎病院（川崎市川崎区・713床）",
      type: "高度急性期・急性期",
      beds: 713,
      salary: "月給30〜39万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "川崎駅徒歩10分",
      ownerType: "公立",
      features: "公立病院・救命救急センター・災害拠点・感染症指定・地域周産期母子医療センター",
      referral: false,
    },
    {
      id: "kanto_rosai",
      displayName: "関東労災病院（川崎市中原区・610床）",
      type: "高度急性期・急性期",
      beds: 610,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "武蔵小杉駅徒歩12分",
      ownerType: "独立行政法人",
      features: "労災病院・地域がん診療連携拠点・地域医療支援病院・教育体制充実",
      referral: false,
    },
    {
      id: "shinyuri_general",
      displayName: "新百合ヶ丘総合病院（川崎市麻生区・563床）",
      type: "高度急性期・急性期",
      beds: 563,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "新百合ヶ丘駅バス5分",
      ownerType: "医療法人",
      features: "がん診療連携拠点・救急告示病院・ロボット手術・教育体制充実",
      referral: false,
    },
    {
      id: "teikyo_mizonokuchi",
      displayName: "帝京大学医学部附属溝口病院（川崎市高津区・400床）",
      type: "急性期",
      beds: 400,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "高津駅徒歩1分",
      ownerType: "学校法人",
      features: "大学病院・駅直結・教育体制充実・研修制度充実・幅広い診療科",
      referral: false,
    },
    {
      id: "kawasaki_ida",
      displayName: "川崎市立井田病院（川崎市中原区・383床）",
      type: "急性期",
      beds: 383,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "日吉駅バス10分",
      emergencyLevel: "二次救急",
      ownerType: "公立",
      features: "公立病院・緩和ケア病棟・地域包括ケア・福利厚生充実・教育体制充実",
      referral: false,
    },
    {
      id: "kawasaki_tama",
      displayName: "川崎市立多摩病院（川崎市多摩区・376床）",
      type: "急性期",
      beds: 376,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "登戸駅徒歩3分",
      emergencyLevel: "二次救急",
      ownerType: "公立",
      features: "公立病院・駅徒歩3分・聖マリアンナ指定管理・地域医療支援・救急告示",
      referral: false,
    },
    {
      id: "nms_musashikosugi",
      displayName: "日本医科大学武蔵小杉病院（川崎市中原区・372床）",
      type: "高度急性期・急性期",
      beds: 372,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "武蔵小杉駅バス5分",
      emergencyLevel: "三次救急",
      ownerType: "学校法人",
      features: "大学病院・救命救急センター・高度医療・教育体制充実・研修充実",
      referral: false,
    },
    {
      id: "kawasaki_saiwai",
      displayName: "川崎幸病院（川崎市幸区・326床）",
      type: "急性期",
      beds: 326,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "川崎駅バス5分",
      emergencyLevel: "二次救急",
      ownerType: "社会医療法人",
      features: "石心会グループ・救急搬送年間1万台・心臓血管外科・24時間救急・教育体制充実",
      referral: false,
    },
    // ===== 新規追加: 川崎 =====
    {
      id: "nkk",
      displayName: "日本鋼管病院（川崎市川崎区・395床）",
      type: "急性期・回復期",
      beds: 395,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（三交代制）",
      commute: "川崎駅バス15分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "aoi_kokusai",
      displayName: "AOI国際病院（川崎市川崎区・328床）",
      type: "高度急性期・急性期・回復期・慢性期",
      beds: 328,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（三交代制）",
      commute: "川崎駅バス10分",
      ownerType: "医療法人",
      features: "高度医療・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "toranomon_bunin",
      displayName: "虎の門病院分院（川崎市高津区・300床）",
      type: "急性期・回復期",
      beds: 300,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（三交代制）",
      commute: "梶が谷駅徒歩15分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "kakio_kinen",
      displayName: "柿生記念病院（川崎市麻生区・270床）",
      type: "慢性期",
      beds: 270,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "柿生駅バス5分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "kawasaki_kyodo",
      displayName: "川崎協同病院（川崎市川崎区・267床）",
      type: "急性期・回復期・慢性期",
      beds: 267,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "川崎駅バス10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "ota_sogo",
      displayName: "太田総合病院（川崎市川崎区・261床）",
      type: "高度急性期・急性期",
      beds: 261,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "川崎駅徒歩3分",
      ownerType: "医療法人",
      features: "高度医療・地域密着",
      referral: false,
    },
    {
      id: "takatsu_chuo",
      displayName: "総合高津中央病院（川崎市高津区・260床）",
      type: "高度急性期・急性期・回復期",
      beds: 260,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "溝の口駅バス10分",
      ownerType: "医療法人",
      features: "高度医療・ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "shinkawabashi",
      displayName: "総合新川橋病院（川崎市川崎区・208床）",
      type: "急性期",
      beds: 208,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "川崎駅バス5分",
      ownerType: "医療法人",
      features: "地域密着",
      referral: false,
    },
    {
      id: "tama_hiyoshidai",
      displayName: "たま日吉台病院（川崎市麻生区・199床）",
      type: "慢性期",
      beds: 199,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "新百合ヶ丘駅バス15分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "asao_sogo",
      displayName: "麻生総合病院（川崎市麻生区・199床）",
      type: "高度急性期・急性期・回復期",
      beds: 199,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "新百合ヶ丘駅バス10分",
      ownerType: "医療法人",
      features: "高度医療・ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "kawasaki_rinko",
      displayName: "川崎臨港病院（川崎市川崎区・199床）",
      type: "高度急性期・急性期",
      beds: 199,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "川崎駅バス15分",
      ownerType: "医療法人",
      features: "高度医療・地域密着",
      referral: false,
    },
    {
      id: "kawasaki_denentoshi",
      displayName: "川崎田園都市病院（川崎市麻生区・194床）",
      type: "慢性期",
      beds: 194,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "新百合ヶ丘駅バス20分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "asao_rehab",
      displayName: "麻生リハビリ総合病院（川崎市麻生区・180床）",
      type: "回復期",
      beds: 180,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "新百合ヶ丘駅バス15分",
      ownerType: "医療法人",
      features: "回復期リハビリ・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "miyagawa",
      displayName: "宮川病院（川崎市川崎区・175床）",
      type: "急性期・回復期・慢性期",
      beds: 175,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "川崎駅バス10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "keihin_sogo",
      displayName: "京浜総合病院（川崎市中原区・140床）",
      type: "急性期・慢性期",
      beds: 140,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "武蔵小杉駅バス10分",
      ownerType: "医療法人",
      features: "地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "kawasaki_midori",
      displayName: "川崎みどりの病院（川崎市麻生区・120床）",
      type: "慢性期",
      beds: 120,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "新百合ヶ丘駅バス15分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    // ===== エージェント調査追加: 川崎 (3施設) =====
    {
      id: "heartful_kawasaki",
      displayName: "ハートフル川崎病院（川崎市高津区・320床）",
      type: "精神科",
      beds: 320,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "溝の口駅バス15分",
      ownerType: "医療法人",
      features: "精神科専門・大規模・残業少なめ",
      referral: false,
    },
    {
      id: "kawasaki_kinen",
      displayName: "かわさき記念病院（川崎市宮前区・300床）",
      type: "精神科",
      beds: 300,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "宮崎台駅バス10分",
      ownerType: "医療法人",
      features: "川崎市初の認知症専門・2014年開院・残業少なめ",
      referral: false,
    },
    {
      id: "toyoko_keiai",
      displayName: "東横惠愛病院（川崎市宮前区・297床）",
      type: "精神科",
      beds: 297,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鷺沼駅徒歩15分",
      ownerType: "一般財団法人",
      features: "聖マリアンナ関連・精神科・送迎バスあり・残業少なめ",
      referral: false,
    },
    // ========== 相模原（相模原市） ==========
    {
      id: "kitasato_univ",
      displayName: "北里大学病院（相模原市南区・1135床）",
      type: "高度急性期・急性期",
      beds: 1135,
      salary: "月給29〜39万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "相模大野駅バス25分",
      ownerType: "学校法人",
      features: "大学病院・特定機能病院・救命救急センター・県内最大規模・教育体制充実",
      referral: false,
    },
    {
      id: "sagamihara_kyodo",
      displayName: "相模原協同病院（相模原市緑区・400床）",
      type: "急性期",
      beds: 400,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "橋本駅バス10分",
      ownerType: "公的",
      features: "JA厚生連・2021年新築移転・がん診療連携拠点・地域医療支援病院・教育体制充実",
      referral: false,
    },
    {
      id: "sagamihara_redcross",
      displayName: "相模原赤十字病院（相模原市緑区・132床）",
      type: "急性期",
      beds: 132,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "橋本駅バス20分",
      ownerType: "赤十字",
      features: "赤十字病院・救急告示病院・災害拠点・地域密着・福利厚生充実",
      referral: false,
    },
    {
      id: "sagamihara_national",
      displayName: "国立病院機構相模原病院（相模原市南区・458床）",
      type: "急性期",
      beds: 458,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "小田急相模原駅バス10分",
      ownerType: "国立病院機構",
      features: "国立病院機構・アレルギー/リウマチ専門・臨床研究・教育体制充実・福利厚生充実",
      referral: false,
    },
    // ===== エージェント調査追加: 相模原 (7施設) =====
    {
      id: "sagamihara_minami",
      displayName: "相模原南病院（相模原市南区・312床）",
      type: "慢性期",
      beds: 312,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "古淵駅徒歩10分",
      ownerType: "医療法人",
      features: "療養型・認知症病棟85床・日勤のみ相談可・残業少なめ",
      referral: false,
    },
    {
      id: "sagami_kosei",
      displayName: "総合相模更生病院（相模原市中央区・225床）",
      type: "急性期",
      beds: 225,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "相模原駅徒歩1分",
      ownerType: "社会福祉法人",
      features: "駅前至近・急性期中心・地域包括ケア44床・地域密着",
      referral: false,
    },
    {
      id: "sagami_rinkan",
      displayName: "さがみ林間病院（相模原市南区・199床）",
      type: "急性期・回復期",
      beds: 199,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "東林間駅徒歩10分",
      ownerType: "医療法人",
      features: "旧東芝林間病院・急性期から回復期まで対応・地域密着",
      referral: false,
    },
    {
      id: "fuchinobe",
      displayName: "渕野辺総合病院（相模原市中央区・161床）",
      type: "急性期・回復期",
      beds: 161,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "淵野辺駅徒歩8分",
      ownerType: "医療法人",
      features: "救急告示病院・地域包括ケア・駅近・地域密着",
      referral: false,
    },
    {
      id: "sagamihara_chuo",
      displayName: "相模原中央病院（相模原市中央区・157床）",
      type: "急性期",
      beds: 157,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "上溝駅バス8分",
      ownerType: "医療法人",
      features: "救急告示病院・地域密着",
      referral: false,
    },
    {
      id: "sagami_rehab",
      displayName: "さがみリハビリテーション病院（相模原市緑区・140床）",
      type: "回復期",
      beds: 140,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "橋本駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ専門・2025年新築移転・日勤のみ相談可",
      referral: false,
    },
    {
      id: "tana",
      displayName: "田名病院（相模原市中央区・120床）",
      type: "慢性期",
      beds: 120,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "原当麻駅バス8分",
      ownerType: "医療法人",
      features: "療養型・介護医療院併設・日勤のみ相談可・残業少なめ",
      referral: false,
    },
    // ========== 横須賀・三浦（横須賀市・鎌倉市） ==========
    {
      id: "yokosuka_kyosai",
      displayName: "横須賀共済病院（横須賀市・740床）",
      type: "高度急性期・急性期",
      beds: 740,
      nurseCount: 795,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "横須賀中央駅徒歩7分",
      ownerType: "公的",
      features: "救命救急センター・地域医療支援病院・災害拠点・がん診療連携拠点・教育体制充実",
      referral: false,
    },
    {
      id: "yokosuka_shimin",
      displayName: "横須賀市立市民病院（横須賀市・339床）",
      type: "急性期",
      beds: 339,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "横須賀中央駅バス35分",
      ownerType: "公立",
      features: "公立病院・地域医療支援病院・災害拠点・救急告示病院・福利厚生充実",
      referral: false,
    },
    {
      id: "shonan_kamakura",
      displayName: "湘南鎌倉総合病院（鎌倉市・669床）",
      type: "高度急性期・急性期",
      beds: 669,
      salary: "月給29〜38万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "大船駅バス7分（無料シャトルあり）",
      ownerType: "医療法人",
      features: "徳洲会・救命救急センター・心臓血管センター・24時間365日救急・教育体制充実",
      referral: false,
    },
    {
      id: "yokosuka_medical_center",
      displayName: "横須賀市立総合医療センター（横須賀市・450床）",
      type: "高度急性期・急性期",
      beds: 450,
      nurseCount: 388,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（三交代制）",
      commute: "京急久里浜駅徒歩7分",
      emergencyLevel: "二次救急",
      ownerType: "公的",
      features: "2025年3月新築開院・ICU12床・34診療科・地域医療振興協会・最新設備",
      referral: false,
    },
    {
      id: "kinugasa",
      displayName: "衣笠病院（横須賀市・198床）",
      type: "ケアミックス",
      beds: 198,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "衣笠駅徒歩5分",
      ownerType: "社会福祉法人",
      features: "1891年創設・駅近・ホスピス（緩和ケア）・地域包括ケア91床・回復期リハ・キリスト教系",
      referral: false,
    },
    // ===== 新規追加: 横須賀・三浦 =====
    {
      id: "pacific_hospital",
      displayName: "パシフィックホスピタル（横須賀市・300床）",
      type: "慢性期",
      beds: 300,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "横須賀中央駅バス20分",
      ownerType: "医療法人",
      features: "療養型・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "ofuna_chuo",
      displayName: "大船中央病院（鎌倉市・247床）",
      type: "急性期・慢性期",
      beds: 247,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（三交代制）",
      commute: "大船駅徒歩5分",
      ownerType: "医療法人",
      features: "地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "kiyokawa",
      displayName: "清川病院（鎌倉市・198床）",
      type: "回復期・慢性期",
      beds: 198,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "大船駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・療養型・徳洲会グループ・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "st_joseph",
      displayName: "聖ヨゼフ病院（横須賀市・182床）",
      type: "急性期・回復期・慢性期",
      beds: 182,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "横須賀中央駅バス10分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "shonan_byoin",
      displayName: "総合病院湘南病院（横須賀市・167床）",
      type: "急性期・回復期・慢性期",
      beds: 167,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "横須賀中央駅バス10分",
      ownerType: "社会福祉法人",
      features: "ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "fureai_kamakura",
      displayName: "ふれあい鎌倉ホスピタル（鎌倉市・156床）",
      type: "急性期・回復期・慢性期",
      beds: 156,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "大船駅バス15分",
      ownerType: "医療法人",
      features: "ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "shonan_kinen",
      displayName: "湘南記念病院（鎌倉市・147床）",
      type: "急性期・回復期・慢性期",
      beds: 147,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "鎌倉駅バス15分",
      ownerType: "医療法人",
      features: "回復期リハビリ・ケアミックス・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "miura_city",
      displayName: "三浦市立病院（三浦市・136床）",
      type: "急性期・回復期",
      beds: 136,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "三崎口駅バス15分",
      ownerType: "公立",
      features: "公立病院・ケアミックス・地域密着",
      referral: false,
    },
    {
      id: "kamakura_rehab_teresa",
      displayName: "鎌倉リハビリテーション聖テレジア病院（鎌倉市・128床）",
      type: "回復期",
      beds: 128,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "大船駅バス10分",
      ownerType: "医療法人",
      features: "回復期リハビリ・地域密着・日勤のみ相談可",
      referral: false,
    },
    {
      id: "suzuki",
      displayName: "鈴木病院（鎌倉市・125床）",
      type: "急性期・慢性期",
      beds: 125,
      salary: "月給26〜34万円（目安）",
      holidays: "年間休日110日以上",
      nightShift: "あり（二交代制）",
      commute: "大船駅バス10分",
      ownerType: "医療法人",
      features: "地域密着・日勤のみ相談可",
      referral: false,
    },

    // ===== エージェント調査追加: 横須賀・三浦 (2施設) =====
    {
      id: "fukui_kinen",
      displayName: "福井記念病院（三浦市・357床）",
      type: "精神科",
      beds: 357,
      salary: "月給28〜37万円（目安）",
      holidays: "年間休日115日以上",
      nightShift: "あり（二交代制）",
      commute: "三浦海岸駅バス8分",
      ownerType: "医療法人",
      features: "精神科・認知症治療・残業少なめ",
      referral: false,
    },
    {
      id: "kurihama",
      displayName: "久里浜医療センター（横須賀市・225床）",
      type: "急性期・精神科",
      beds: 225,
      salary: "月給27〜35万円（目安）",
      holidays: "年間休日120日以上",
      nightShift: "あり（二交代制）",
      commute: "京急久里浜駅バス10分",
      ownerType: "国立病院機構",
      features: "国立病院機構・依存症治療の日本最高峰・WHO協力センター・教育体制充実",
      referral: false,
    },
  ],

  // 外部API連携（実運用時に設定）
  API: {
    workerEndpoint: "https://robby-the-match-api.robby-the-robot-2026.workers.dev",        // Cloudflare Workers API URL
    slackWebhookUrl: "",       // Slack Webhook URL（レガシー：workerEndpoint設定後は不要）
    googleSheetsId: "",        // Google Sheets ID（レガシー：workerEndpoint設定後は不要）
  },

  // デザイン設定
  DESIGN: {
    primaryBg: "#FAFAF2",
    secondaryBg: "#F2EFE6",
    accentColor: "#5B787D",
    accentSecondary: "#8FB5A1",
    accentHover: "#4A6368",
    textPrimary: "#4A4A4A",
    textSecondary: "#7A7A7A",
    cardBg: "#FFFFFF",
    borderColor: "#D4CFC2",
  },
};
